name: Build & Release CommandReplacer

on:
  push:
    branches: [ main, master ]
    tags:
      - '*'      # 任意 tag，比如 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar-name: ${{ steps.rename.outputs.jar }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Ensure Gradle wrapper exists
        run: |
          if [ ! -f gradlew ]; then
            echo ">> no gradlew found, installing system gradle to generate wrapper"
            sudo apt-get update && sudo apt-get install -y gradle
            # 4.4.1 对应 ForgeGradle 2.2 要求，且不含 --add-opens 参数
            gradle wrapper --gradle-version 4.4.1
          fi

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build mod with Gradle wrapper
        run: ./gradlew build --quiet --no-daemon

      - name: Rename JAR to include MC & mod version
        id: rename
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TARGET="cmdreplacer_1.8.9_${TAG}.jar"
          mv build/libs/cmdreplacer-*.jar build/libs/${TARGET}
          echo "jar=${TARGET}" >> $GITHUB_OUTPUT

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "CommandReplacer ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload mod JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/${{ needs.build.outputs.jar-name }}
          asset_name: ${{ needs.build.outputs.jar-name }}
          asset_content_type: application/java-archive
